services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ★ 常駐させる（Dev Containersが接続できるように）
    command: ["sleep", "infinity"]
    init: true
    tty: true

    # LinuxでBLEを使うための設定（DBus共有＋hostネットワーク）
    network_mode: host
    volumes:
      - ..:/workspaces/workspace:cached
      - /var/run/dbus:/var/run/dbus
    environment:
      - MQTT_BROKER=tcp://127.0.0.1:11883
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket  # system bus を明示
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - apparmor=unconfined
    working_dir: /workspaces/workspace
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:2
    network_mode: host
    volumes:
      - ./mosquitto:/mosquitto/config:ro
    restart: unless-stopped
